$schema: http://json-schema.org/draft-07/schema#

type: object
properties:
  restaurants:
    type: object
    additionalProperties:
      $ref: '#/$defs/restaurant'

$defs:
  restaurant:
    type: object
    required:
      - cuisine
      - tables
    properties:
      cuisine:
        type: string
        format: string
    tables:
      type: array
      items:
        $ref: '#/$defs/table'
  table:
    type: object
    required:
      - seats
    properties:
      seats:
        type: number
        minimum: 2
        maximum: 10
      view:
        type: boolean