apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-postgres
  labels: 
    app: blue-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-postgres
  template:
    metadata:
      labels:
        app: blue-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15.2
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: blue-postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: blue-postgres-pv-claim

---

apiVersion: v1
kind: Service
metadata:
  name: blue-postgres
  labels:
    app: blue-postgres
spec:
  selector:
    app: blue-postgres
  type: LoadBalancer
  ports:
   - port: 5432
     nodePort: 31543
